### ISSUE TITLE
Support for Multiple Services

### ISSUE THREAD

**Issue by jverlee** [BreezeChMS/livebar#11]
Livebar currently supports two services, although only one is documented. There's two needs then:

1) Supporting more than 2 services (perhaps up to 5 or a clever way of having infinite services)?

2) A smooth way to document this on the index.html page so less technical users can generate the code for multiple services (the index.html page is what users see at https://livebar.church and so updating that file will update that page).

**Comment by christianpatrick** [comment]
@jverlee, I've added in the ability to accomplish this with PR #15. Feel free to take a peek at your convenience and let me know if you find any issues with it. 😄
